### ISSUE TITLE
Cannot shield transparent coins

### ISSUE THREAD

**Issue by BTCapsule** [LayerTwo-Labs/zcash-sidechain#21]
When I try to shield transparent coins, a popup appears that says it was successful. However, under Operation Statuses it says it failed because change is not allowed ![image](https://github.com/LayerTwo-Labs/zcash-sidechain/assets/115264270/41e77255-1990-4c01-b4c8-6751105a3768)

**Comment by octobocto** [comment]
Fixed some time ago. Thanks for reporting. This issue can be closed.
